name: GitHub Pages Deployment

on:
  workflow_dispatch:
  workflow_run:
    branches:
      - master
    types:
      - completed
    workflows:
      - JS Checks

permissions:
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: hemilabs/actions/setup-node-env@v1
      - run: cd website && npm run build
        env:
          VITE_WALLET_CONNECT_PROJECT_ID: ${{ vars.VITE_WALLET_CONNECT_PROJECT_ID }}
          VITE_WALLET_CONNECT_PROJECT_NAME: ${{ vars.VITE_WALLET_CONNECT_PROJECT_NAME }}
      - id: deployment
        uses: hemilabs/actions/deploy-to-ghp@3018c41d5e6f18de555804303ab3d0402e670f98 # PR#24
        with:
          publish-dir: website/dist
    timeout-minutes: 2
